config/routes.rb
Rails.application.routes.draw do
  
  root to:'subjects#index'
  
  resources :subjects do
    member do
      get :delete
    end
  end

  get 'demo/index'

  #get ':controller(/:action(:/id))'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord

    scope :sorted, lambda { order("title ASC") }
    scope :newest_first, lambda { order("created_at DESC") }
    scope :search, lambda {|query| where(["Title LIKE ?", "%#{query}%"]) }

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  
  layout false
  
  def index
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:title => 'Default'})
  end

  def create
    @subject = Subject.new(subject_params)
    
    if @subject.save

      flash[:notice] = "Book added successfully."
      redirect_to(subjects_path)
    else
      
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])

    if @subject.update_attributes(subject_params)
      flash[:notice] = "Book updated successfully."
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "'#{@subject.title}' removed successfully."
    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:title, :author, :genre, :price, :publishdate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/views/demo/index.html.erb
<h1>Hello world</h1>
#<h1>Demo#index</h1>
#<p>Find me in app/views/demo/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pa3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to Main", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Book</h2>

  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this Book?</p>

    <p class="reference-name"><%= f.object.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to Main", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Book Information</h2>

  <%= form_for(@subject) do |f| %>

    <table summary="Subject form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.select(:genre, ['Action', 'Adventure', 'Alternate history','Autobiography', 'Business' 'Childrens','Classic','Comedy','Comic','Crime','Drama','Fanatasy','History','Historical fiction','Horror']) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Publish Date</th>
        <td><%= f.date_select(:publishdate) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Book Information") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<style>
table, th, td {
  border: 1px solid black;
}
</style>

<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="subjects index">
  <h2>Book Store</h2>

  <%= link_to("Add New Book", new_subject_path, :class => 'action new') %>

  <table style = "width:100%" class="listing" summary="Subject list">
    <tr class="header">
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Price</th>
      <th>Publish_Date</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.title %></td>
      <td><%= subject.author %></td>
      <td><%= subject.genre %></td>
      <td><%= subject.price %></td>
      <td><%= subject.publishdate %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to Main", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Add a Book</h2>

  <%= form_for(@subject) do |f| %>

    <table summary="Subject form fields">
      <tr>
        <th>Book Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.select(:genre, ['Action', 'Adventure', 'Alternate history','Autobiography', 'Business' 'Childrens','Classic','Comedy','Comic','Crime','Drama','Fanatasy','History','Historical fiction','Horror']) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Publish Date</th>
        <td><%= f.date_select(:publishdate) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/show.html.erb
<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= link_to("<< Back to Main", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Book Information</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Title</th>
      <td><%= @subject.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @subject.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @subject.genre %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @subject.price %></td>
    </tr>
    <tr>
      <th>Publish Date</th>
      <td><%= @subject.publishdate %></td>
    </tr>
  </table>

</div>